### ISSUE TITLE
Package still maintained or ?

### ISSUE THREAD

**Issue by ossycodes** [mikeemoo/ColorJizz-PHP#17]
@mikeemoo @azettl @ReactiveRaven @vredeling is this project still Active please ? I face some deprecations issues when using PHP 8.1 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/55060799/225603935-76048e1b-e91c-4b85-b100-7e84468b8a6c.png">

If it's maintained/active I can open a PR to fix these issues

**Comment by ossycodes** [comment]
@drake-p @adduc @petrhanak

**Comment by vredeling** [comment]
@ossycodes Not sure if it's still under development. I'm not a maintainer myself. The project feels quite stale, so I'd say: just fork the project and propose some MRs if you want to proceed.

**Comment by ossycodes** [comment]
@vredeling got it thanks!
